# Use postgres/example user/password credentials
version: '3.9'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:password1@db:5432/goji_interview
      NODE_ENV: production
      PORT: 3002
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3002:3002'

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: goji_interview
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d goji_interview"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
